default_platform(:ios)

platform :ios do
  desc "Submit app for review"
  lane :submit_for_review do
    deliver(
      app_identifier: "com.williaml33.ReignScore",
      submit_for_review: true,
      automatic_release: true,
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_metadata: true,
      force: true,
      submission_information: {
        add_id_info_uses_idfa: false,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: true,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_contains_third_party_cryptography: false,
        content_rights_contains_third_party_content: false,
        content_rights_has_rights: true
      }
    )
  end
end
